alias ag="env RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc" rg -.i"
alias cat="bat -pp"
alias chmod="chmod -c --preserve-root"
alias cls="clear"
alias cp="cp -airv"
alias dd="dd status=progress"
alias df="df -h"
alias du="du -h"
alias fd="fd -Hi"
alias grep="ag"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias rg="ag"
alias ps="procs -t"
alias sudo="sudo "
